services:
  _defaults:
    autowire: true
    autoconfigure: true

  Nachoaguirre\WassengerBundle\Contract\ProviderInterface:
    alias: Nachoaguirre\WassengerBundle\Provider\WassengerProvider
    public: true

  Nachoaguirre\WassengerBundle\EventSubscriber\GreetingsSubscriber: ~

  Nachoaguirre\WassengerBundle\Service\PhoneNumberNormalizer: ~

  Nachoaguirre\WassengerBundle\Registry\RecipientRegistry:
    public: true

  Nachoaguirre\WassengerBundle\Provider\WassengerProvider:
    arguments:
      $httpClient: "@http_client"

  Nachoaguirre\WassengerBundle\Command\WassengerSetupCommand: ~

  Nachoaguirre\WassengerBundle\Controller\WebhookController:
    public: true
    arguments:
      $eventDispatcher: "@event_dispatcher"
    tags: ["controller.service_arguments"]
